version: '3.3'

services:
  barkeep:
    build: .
    networks:
      - default 
    ports:
      - 5000:5000
    volumes:
      - ./data:/code/data
    working_dir: /code

  mysql:
    image: arm64v8/mysql
    networks:
      -  default
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'barkeep'
      MYSQL_USER: 'barkeep_user'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: 'changeme'

volumes:
  mysql:

networks:
  default:
